info:
  version: 1.0.0
  title: apic-product-ddd
  name: apic-product-ddd
gateways:
  - datapower-api-gateway
plans:
  default-plan:
    rate-limits:
      default:
        value: 100/1hour
    title: Default Plan
    description: Default Plan
    approval: false
  gold-plan:
    rate-limits:
      default:
        value: 10/1second
    title: Gold Plan
    description: Gold Plan for Valued Customers
    approval: false
visibility:
  view:
    type: public
    orgs: []
    tags: []
    enabled: true
  subscribe:
    type: authenticated
    orgs: []
    tags: []
    enabled: true
product: 1.0.0
apis:
  drivewaydentdeletion2.0.0:
    name: "drivewaydentdeletion:2.0.0"
